@echo off
REM Rollback script generated by migrate-docs-separation.js
REM Backup location: D:\github_projects\SoloDevFlow2\.backups\migration-v4.1-2025-12-22T06-54-21

echo Rolling back documentation structure migration...

REM Remove new directories
if exist "D:\github_projects\SoloDevFlow2\docs\requirements" rmdir /S /Q "D:\github_projects\SoloDevFlow2\docs\requirements"
if exist "D:\github_projects\SoloDevFlow2\docs\designs" rmdir /S /Q "D:\github_projects\SoloDevFlow2\docs\designs"

REM Restore from backup
xcopy "D:\github_projects\SoloDevFlow2\.backups\migration-v4.1-2025-12-22T06-54-21\docs" "D:\github_projects\SoloDevFlow2\docs" /E /I /H /Y
if exist "D:\github_projects\SoloDevFlow2\.backups\migration-v4.1-2025-12-22T06-54-21\state.json" copy /Y "D:\github_projects\SoloDevFlow2\.backups\migration-v4.1-2025-12-22T06-54-21\state.json" "D:\github_projects\SoloDevFlow2\.flow\state.json"

echo Rollback completed!
pause
